spring.application.name=user-ws
server.port=0

# Eureka
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${spring.application.name}:${random.value}

# DevTools opcional
spring.devtools.restart.enabled=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

jwt.secret="chave-super-secreta-com-pelo-menos-32-bytes"
jwt.expiration=3600000
jwt.issuer="auth-service
jwt.refresh-expiration= 8600000
